### ISSUE TITLE
Changing hotkey causes error: "hotkey_toggle_highlights": "Ctrl+T, H"

### ISSUE THREAD

**Issue by Apocalypse612** [glutanimate/highlight-search-results#16] opened 2022-12-31 04:37 UTC
#### Problem description

Changing the following config value produces an error: "hotkey_toggle_highlights": "Ctrl+T, H"

It also prevents any change to the hotkey.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
    Platform: Windows 10
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2022-12-30 22:13:10
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['popup_dictionary', 0, 'None', '']
    Add Hyperlink ['318752047', 2022-05-23T09:16, 'None', '']
    Adjust Sound Volume ['2123044452', 2021-05-05T07:24, 'None', mod]
    Advanced Browser ['874215009', 2022-09-26T20:28, 'None', '']
    Asset Manager ['656021484', 2021-08-29T17:07, 'None', '']
    AwesomeTTS ['awesometts', 0, 'None', '']
    Batch Editing ['291119185', 2019-06-02T14:47, 'None', '']
    BetterSearch ['1052724801', 2022-01-25T17:25, 'None', '']
    Button Colours Good Again ['2494384865', 2022-09-27T06:18, 'None', mod]
    Cloze Overlapper for Anki 21 ['109531687', 2021-01-11T22:12, 'None', '']
    Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T11:06, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2022-09-14T05:12, 'None', mod]
    Duplicate and Reorder ['1114271285', 2022-06-29T17:05, 'None', '']
    Edit Field During Review Cloze ['385888438', 2022-06-27T05:48, '6.13', mod]
    Fastbar- with nightmode support ['46611790', 2022-11-28T08:10, 'None', '']
    Find and Replace in Card templatesNotetypesHTML ['992153575', 2021-09-17T02:34, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-10T12:06, 'None', '']
    Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
    MassAdd - Create multiple cards from raw text ['1909156369', 2021-08-16T09:26, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T13:45, 'None', '']
    Quick Colour Changing ['2491935955', 2022-07-24T00:29, 'None', mod]
    Remaining time for Anki 21 ['1508357010', 2020-12-13T09:14, '20.12.13i151', '']
    Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']
    Search Bar ['1251668918', 2020-09-09T17:55, 'None', '']
    Tippy Tooltips ['1840818335', 2022-04-10T11:50, 'None', '']
    Web Browser - Search terms Import texts and images automatically ['864545277', 2022-08-02T16:49, 'None', mod]
    add-on dialog searchfilter bar ['561945101', 2021-12-05T15:28, 'None', '']
    editor - remove more formatting for selection headings hyperlinks ['333221628', 2019-04-10T18:45, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1052724801 109531687 1114271285 1251668918 1374772155 1508357010 1771074083 1840818335 1909156369 2123044452 225180905 24411424 2491935955 2494384865 291119185 295889520 318752047 333221628 385888438 46611790 561945101 594329229 656021484 864545277 874215009 992153575
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
![image](https://user-images.githubusercontent.com/6374154/210124993-08f15508-98e6-4fa8-9b7a-13a21ebc1703.png)
```

**Comment by galantra** [comment] 2022-12-31 06:56
Same error as https://github.com/glutanimate/highlight-search-results/issues/11

**Comment by Apocalypse612** [comment] 2022-12-31 14:30
Apologies, I missed it.

**Comment by glutanimate** [comment] 2022-12-31 15:41
Thanks for the reports, guys. Looks like the config validation is no longer working correctly in recent Anki releases. Will look into it.

Closing as duplicate of #11

**Closed by glutanimate** 2022-12-31 15:41 UTC
Labels: bug
